var jsonData = [
    {
      "q" : " HTML is the standard ____language for creating Web pages.",
      "opt1" : "scripting",
      "opt2" : "programming",
      "opt3" : "styling",
      "opt4" : "markup",
      "answer" : "opt4",
    },
    {
        "q" : " HTML stands for_______.",
        "opt1" : "Hyperactive Text Markup Language",
        "opt2" : "Hyper Text Markup Language",
        "opt3" : "Hyper Text Machine Language",
        "opt4" : "None of these",
        "answer" : "opt2",
      },
      {
        "q" : " Which attribute specifies an alternate text for the image?",
        "opt1" : "alt",
        "opt2" : "alternate",
        "opt3" : "alttext",
        "opt4" : "All of the above",
        "answer" : "opt2",
      },
      {
        "q" : "Which attribute is used to specify a unique id for an HTML element?",
        "opt1" : "style",
        "opt2" : "css",
        "opt3" : "id",
        "opt4" : "class",
        "answer" : "opt3",
      },
      {
        "q" : " Which is the correct syntax to include comment in an HTML document?",
        "opt1" : "//",
        "opt2" : "/* Comment */ ",
        "opt3" : "// Comment //",
        "opt4" : "!-- Comment --",
        "answer" : "opt4",
      },
      {
        "q" : "Can we hide inline content using the comment?",
        "opt1" : "Yes",
        "opt2" : "No",
        "answer" : "opt1",
      },
      {
        "q" : "Can we hide content using the comment?",
        "opt1" : "Yes",
        "opt2" : "No",
        "answer" : "opt1",
      },
      {
        "q" : "HTML tags with no content are called _____.",
        "opt1" : "Special tags",
        "opt2" : "Advanced tags",
        "opt3" : "Empty tags",
        "opt4" : "Other tags",
        "answer" : "opt3",
      },
      
      {
        "q" : "Who invented HTML?",
        "opt1" : "Dave Raggett",
        "opt2" : "Tim Berners-Lee",
        "opt3" : "Denis Ritchie",
        "opt4" : "All of the above",
        "answer" : "opt2",
      },
      
      {
        "q" : "Which ____ attribute specifies where to open the linked document?",
        "opt1" : "href",
        "opt2" : "link",
        "opt3" : "src",
        "opt4" : "target",
        "answer" : "opt4",
      },
]; 